stripe.publishable.key=pk_test_51TOp3XFqyyoTbBrw8E01GrS5yoOnZu2FzOlk8exyZuYH24lbRBmLMgYBApCi5HKUpAHkkSsS3ZxKz4HizSYM93gE00kAwf8e1J
stripe.secret.key=sk_test_51TOp3XFqyyoTbBrwv34JwJUE9BJ7P0qkNxJ5iYcqiYVvTY0zKEesl74fZjl1pahi2pRX6PhHbcO7ZusTrxsILQwj00tjPwmYA1
# Other configs...
db.url=jdbc:mysql://localhost:3306/eyetwin
db.user=root
db.password=
